# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IRTlikRcppA <- function(par, data, pen, nodes, weights, lambda = 0) {
    .Call(`_S3PL_IRTlikRcppA`, par, data, pen, nodes, weights, lambda)
}

gradIRTlikRcppA <- function(par, data, pen, nodes, weights, lambda = 0) {
    .Call(`_S3PL_gradIRTlikRcppA`, par, data, pen, nodes, weights, lambda)
}

grad_i_IRTlikRcppA <- function(par, data, pen, nodes, weights, lambda = 0) {
    .Call(`_S3PL_grad_i_IRTlikRcppA`, par, data, pen, nodes, weights, lambda)
}

